#define BINARY_OP_ADD_FLOAT                      6
#define BINARY_OP_ADD_INT                        7
#define BINARY_OP_ADD_UNICODE                    8
#define BINARY_OP_INPLACE_ADD_UNICODE           10
#define BINARY_OP_MULTIPLY_FLOAT                13
#define BINARY_OP_MULTIPLY_INT                  14
#define BINARY_OP_SUBTRACT_FLOAT                16
#define BINARY_OP_SUBTRACT_INT                  18
#define BINARY_SUBSCR_DICT                      19
#define BINARY_SUBSCR_GETITEM                   20
#define BINARY_SUBSCR_LIST_INT                  21
#define BINARY_SUBSCR_TUPLE_INT                 22
#define CALL_PY_EXACT_ARGS                      23
#define CALL_PY_WITH_DEFAULTS                   24
#define CALL_BOUND_METHOD_EXACT_ARGS            28
#define CALL_BUILTIN_CLASS                      29
#define CALL_BUILTIN_FAST_WITH_KEYWORDS         34
#define CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS  38
#define CALL_NO_KW_BUILTIN_FAST                 39
#define CALL_NO_KW_BUILTIN_O                    40
#define CALL_NO_KW_ISINSTANCE                   41
#define CALL_NO_KW_LEN                          42
#define CALL_NO_KW_LIST_APPEND                  43
#define CALL_NO_KW_METHOD_DESCRIPTOR_FAST       44
#define CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS     45
#define CALL_NO_KW_METHOD_DESCRIPTOR_O          46
#define CALL_NO_KW_STR_1                        47
#define CALL_NO_KW_TUPLE_1                      48
#define CALL_NO_KW_TYPE_1                       56
#define COMPARE_OP_FLOAT                        57
#define COMPARE_OP_INT                          58
#define COMPARE_OP_STR                          59
#define FOR_ITER_LIST                           62
#define FOR_ITER_TUPLE                          63
#define FOR_ITER_RANGE                          64
#define FOR_ITER_GEN                            65
#define LOAD_SUPER_ATTR_ATTR                    66
#define LOAD_SUPER_ATTR_METHOD                  67
#define LOAD_ATTR_CLASS                         70
#define LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN       72
#define LOAD_ATTR_INSTANCE_VALUE                73
#define LOAD_ATTR_MODULE                        76
#define LOAD_ATTR_PROPERTY                      77
#define LOAD_ATTR_SLOT                          78
#define LOAD_ATTR_WITH_HINT                     79
#define LOAD_ATTR_METHOD_LAZY_DICT              80
#define LOAD_ATTR_METHOD_NO_DICT                81
#define LOAD_ATTR_METHOD_WITH_VALUES            82
#define LOAD_CONST__LOAD_FAST                   84
#define LOAD_FAST__LOAD_CONST                   86
#define LOAD_FAST__LOAD_FAST                    88
#define LOAD_GLOBAL_BUILTIN                    111
#define LOAD_GLOBAL_MODULE                     112
#define STORE_ATTR_INSTANCE_VALUE              113
#define STORE_ATTR_SLOT                        148
#define STORE_ATTR_WITH_HINT                   153
#define STORE_FAST__LOAD_FAST                  154
#define STORE_FAST__STORE_FAST                 158
#define STORE_SUBSCR_DICT                      159
#define STORE_SUBSCR_LIST_INT                  160
#define UNPACK_SEQUENCE_LIST                   161
#define UNPACK_SEQUENCE_TUPLE                  166
#define UNPACK_SEQUENCE_TWO_TUPLE              167
#define SEND_GEN                               168