# fly.toml app configuration file generated for ret2dlresolve on 2024-07-22T22:18:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ret2dlresolve'
primary_region = 'sjc'

[build]

[[services]]
  internal_port = 5000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 5000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
